####################################################################################################################################
# Useful links:
#
# Cloud Text To Speech
# https://cloud.google.com/text-to-speech/docs/voices
#
# âš ï¸ The "name" attribute should never be updated without migrations (fields user.platform, category.platform, badge.platform,
#    structure.platform, volunteer.platform on the db are tied to it).
#
# âš ï¸ When adding a new platform, do not forget to add it in the platform enum, App\Enum\Platform
#
# âš ï¸ When adding a new platform, do not forget to add it in the platform facade, App\Facade\Generic\PlatformFacade
#
# âš ï¸ When adding a new platform, do not forget to add its phone value in "phones.yaml"
####################################################################################################################################
parameters:
  platforms:
    - name: fr
      label: France
      language: fr
      phone: fr
      timezone: 'Europe/Paris'
      flag: ğŸ‡«ğŸ‡·
#    - name: es
#      label: EspaÃ±a
#      language: es
#      phone: es
#      timezone: 'Europe/Madrid'
#      flag: ğŸ‡ªğŸ‡¸
#    - name: pt
#      label: Portugal
#      language: pt
#      phone: pt
#      timezone: 'Europe/Lisbon'
#      flag: ğŸ‡µğŸ‡¹
