services:

    # Inject this service in your controllers/services to verify a submitted captcha.
    ReCaptcha\ReCaptcha:
        arguments:
            $secret: '%env(GOOGLE_RECAPTCHA_SECRET)%'

    # Curl is set here as default transport to communicate with Google servers.
    # If you do not have php-curl extension, you can change for a socket or a plain POST request.
    # Check out the repository for all other request methods:
    # https://github.com/google/recaptcha/tree/master/src/ReCaptcha/RequestMethod
    ReCaptcha\RequestMethod: '@ReCaptcha\RequestMethod\CurlPost'
    ReCaptcha\RequestMethod\CurlPost: ~
    ReCaptcha\RequestMethod\Curl: ~

ewz_recaptcha:
    public_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    private_key: '%env(GOOGLE_RECAPTCHA_SECRET)%'
    locale_from_request: true

