twig:
  paths: ['%kernel.project_dir%/templates']
  debug: '%kernel.debug%'
  strict_variables: '%kernel.debug%'
  form_themes:
  - 'bootstrap_4_layout.html.twig'
  - 'form_theme.html.twig'
  globals:
    is_redcross: '%env(IS_REDCROSS)%'
    minutis_url: '%env(MINUTIS_URL)%'
    red: '%env(COLOR_RED)%'
    darkgrey: '%env(COLOR_DARKGREY)%'
    lightgrey: '%env(COLOR_LIGHTGREY)%'
    coolgrey: '%env(COLOR_COOLGREY)%'
    offwhite: '%env(COLOR_OFFWHITE)%'
    logo: '%env(LOGO)%'
    brand: '%env(BRAND)%'
